//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mdlDudunBot
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Finance
    {
        public Nullable<int> Id { get; set; }
        public string Source { get; set; }

        [DataType(DataType.Currency)]
        public int Nominal { get; set; }

        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        public string Type { get; set; }
    }

    public enum CategoryFinance
    {
        Income,
        Outcome,
        Saving,
        Rent_In,
        Rent_Out
    }
}
